blog/travels/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired


class TravelForm (FlaskForm) :
    destination= StringField('Destination',
                        validators=[DataRequired()])
    budget = StringField('Budget',
                        validators=[DataRequired()])
    duration = StringField('Duration in days',
                        validators=[DataRequired()])
    participants = StringField('Participants',
                        validators=[DataRequired()])
    description = StringField('Type of travel',
                        validators=[DataRequired()])
    submit = SubmitField('Create Travel')

blog/travels/routes.py
from flask import render_template, request, Blueprint, redirect, url_for, flash
from flask_login import current_user

from blog import db
from models import Travel
from travels.forms import TravelForm

travels = Blueprint('travels', __name__)


@travels.route("/travel" , methods=['GET', 'POST'])
def travel():
    if not current_user.is_authenticated:
        flash('You have to be logged in COZZONE!', 'danger')
        return redirect(url_for('main.home'))
    form = TravelForm()
    if form.validate_on_submit():
        new_travel = Travel(destination=form.destination.data, duration=form.duration.data, budget=form.budget.data,
                            participants=form.participants.data,description = form.description.data, user_id=current_user.id,
                            user_email = current_user.email)
        db.session.add(new_travel)
        db.session.commit()
        flash('Your travel has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('travel.html', title='Travel creation', form=form)

blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, app
from flask_login import login_user, current_user, logout_user, login_required
from blog import db, bcrypt
from blog.models import User, Post
from blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        pass1 = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user=User(username=form.username.data,email=form.email.data,password=pass1, idCard=form.id.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.account'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

blog/templates/about.html
    <h1>About Page</h1>

blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
   <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{current_user.username}}</h2>
          <p class="text-secondary">{{current_user.email}}</p>
        </div>
      </div>
        <form method="post" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
         <fieldset class="form-group">
             <legend class="border-bottom mb-4">Account Info</legend>
             <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
             <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
             <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
             </div>







         </fieldset>
         <div class="form-group">
                 {{ form.submit(class="btn btn-outline-info") }}
             </div>
     </form>
   </div>
{% endblock content %}

blog/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted }}</small>
        </div>
        <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% endblock content %}
{% block feed %}
{% for travel in travels.items %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">{{ travel.date_posted.strftime('%Y-%m-%d') }}</small>
            <small class="text-muted">{{travel.user_id }}</small>

        </div>
        <h2><a class="article-title" href="{{ url_for('travels.travel', travel_id=travel.id) }}">{{ travel.destination
            }}</a></h2>
        <p class="article-content">Type of travel: {{ travel.description }}</p>
         <p class="article-content">Budget: {{ travel.budget }}</p>
        <p class="article-content">Email creator: {{ travel.user_email }}</p>

    </div>
</article>
{% endfor %}
{% endblock feed %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link href="offcanvas.css" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/offcanvas/">
        <link rel="stylesheet" type="text/css" href="custom.css">



    {% if title %}
    <title> Travel - {{ title }} </title>
    {% else %}
    <title>Travel</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">JoinTheTravel</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('travels.travel') }}">Travel</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
           {% block feed %}{% endblock %}
            </div>
        </div>
    </div>
</div>
 <footer>
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
            <p>The journey of a thousand miles begins with a single step.</p>
          Matteo La Rosa, Benedetta La Rosa, Tommaso Scarrone, Gianluca Savina, Edoardo Di Lauro, Davide Iovino

        </div>
  		</div>
  	</div>
  </footer>

</body>

blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
   <div class="content-section">
     <form method="post" action="">
       {{ form.hidden_tag() }}
         <fieldset class="form-group">
             <legend class="border-bottom mb-4">Log In</legend>

             <div class="form-group">
                 {{ form.email.label(class="form-control-label") }}
                 {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.email(class="form-control form-control-lg") }}

                 {% endif %}
             </div>
             <div class="form-group">
                 {{ form.password.label(class="form-control-label") }}
                 {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.password(class="form-control form-control-lg") }}

                 {% endif %}
             </div>
             <div class="form-chech">
                 {{ form.remember(class="form-check-input") }}
                 {{ form.remember.label(class="form-check-label") }}
             </div>
         </fieldset>
         <div class="form-group">
                 {{ form.submit(class="btn btn-outline-info") }}
             </div>
             <small class="text-muted ml-2">
                 <a href="#">Forgot Password?</a>
             </small>
     </form>
   </div>
    <div class="border-top pt-3">
        <small class="text-muted">
             Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>


    </div>
{% endblock content %}

blog/templates/register.html
{% extends "layout.html" %}
{% block content %}
   <div class="content-section">
     <form method="post" action="">
         {% if form.errors %}
         {{form.errors}}
         {%endif%}
         {{ form.hidden_tag() }}
         {{form.csrf_token }}
         <fieldset class="form-group">
             <legend class="border-bottom mb-4">Join Today</legend>
             <div class="form-group">
                 {{ form.name.label(class="form-control-label") }}
                 {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.name(class="form-control form-control-lg") }}
                 {% endif %}
             </div>
             <div class="form-group">
                 {{ form.surname.label(class="form-control-label") }}
                 {% if form.surname.errors %}
                    {{ form.surname(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.surname.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.surname(class="form-control form-control-lg") }}
                 {% endif %}
             </div>
             <div class="form-group">
                 {{ form.id.label(class="form-control-label") }}
                 {% if form.id.errors %}
                    {{ form.id(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.id(class="form-control form-control-lg") }}
                 {% endif %}

             <div class="form-group">
                 {{ form.username.label(class="form-control-label") }}
                 {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                 {% endif %}
             </div>
             <div class="form-group">
                 {{ form.email.label(class="form-control-label") }}
                 {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.email(class="form-control form-control-lg") }}

                 {% endif %}
             </div>
             <div class="form-group">
                 {{ form.password.label(class="form-control-label") }}
                 {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.password(class="form-control form-control-lg") }}

                 {% endif %}
             </div>
             <div class="form-group">
                 {{ form.confirm_password.label(class="form-control-label") }}
                 {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                     <div class="invalid-feedback">
                        {% for errors in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                     </div>
                     {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}

                 {% endif %}
             </div>
         </fieldset>
         <div class="form-group">
                 {{ form.submit(class="btn btn-outline-info") }}

             </div>
     </form>
   </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>


    </div>
{% endblock content %}

blog/templates/travel.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="post" action="">
        {% if form.errors %}
        {{form.errors}}
        {%endif%}
        {{ form.hidden_tag() }}
        {{form.csrf_token }}
        <fieldset class="input-group">
            <legend class="border-bottom mb-4">Travel Page</legend>

             <div name="citta" class="form-group">
                {{ form.destination.label(class="form-control-label") }}
                {% if form.destination.errors %}
                {{ form.destination(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for errors in form.destination.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.destination(class="form-control form-control-lg") }}
                {% endif %}
            </div>

              <div class="form-group">
                {{ form.budget.label(class="form-control-label") }}
                {% if form.budget.errors %}
                {{ form.budget(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for errors in form.budget.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.budget(class="form-control form-control-lg") }}
                {% endif %}
            </div>

              <div class="form-group">
                {{ form.duration.label(class="form-control-label") }}
                {% if form.duration.errors %}
                {{ form.duration(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for errors in form.duration.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.duration(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.participants.label(class="form-control-label") }}
                {% if form.participants.errors %}
                {{ form.participants(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for errors in form.participants.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.participants(class="form-control form-control-lg") }}
                {% endif %}
            </div>
              <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for errors in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>


        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}